// <auto-generated />
using System;
using Aogiri.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aogiri.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260429080757_AddSubcategoriesAndAttributes")]
    partial class AddSubcategoriesAndAttributes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Aogiri.Models.ActivityLog", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogID"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("LogID");

                    b.HasIndex("UserID");

                    b.ToTable("ActivityLog_7", (string)null);
                });

            modelBuilder.Entity("Aogiri.Models.AdAttribute", b =>
                {
                    b.Property<int>("AdAttributeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdAttributeID"));

                    b.Property<int>("AdID")
                        .HasColumnType("int");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdAttributeID");

                    b.HasIndex("AdID");

                    b.ToTable("AdAttribute_12", (string)null);
                });

            modelBuilder.Entity("Aogiri.Models.AdImage", b =>
                {
                    b.Property<int>("AdImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdImageID"));

                    b.Property<int>("AdID")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("AdImageID");

                    b.HasIndex("AdID");

                    b.ToTable("AdImage_10", (string)null);
                });

            modelBuilder.Entity("Aogiri.Models.Advertisement", b =>
                {
                    b.Property<int>("AdID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Condition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DealType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocationID")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<DateTime>("PublishedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Draft");

                    b.Property<int?>("SubcategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("AdID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("LocationID");

                    b.HasIndex("SubcategoryID");

                    b.HasIndex("UserID");

                    b.ToTable("Advertisement_4", (string)null);
                });

            modelBuilder.Entity("Aogiri.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("IconClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Category_2", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            IconClass = "bi-car-front",
                            Name = "Транспорт"
                        },
                        new
                        {
                            CategoryID = 2,
                            IconClass = "bi-house",
                            Name = "Недвижимость"
                        },
                        new
                        {
                            CategoryID = 3,
                            IconClass = "bi-laptop",
                            Name = "Электроника"
                        },
                        new
                        {
                            CategoryID = 4,
                            IconClass = "bi-bag",
                            Name = "Одежда и обувь"
                        },
                        new
                        {
                            CategoryID = 5,
                            IconClass = "bi-briefcase",
                            Name = "Работа"
                        },
                        new
                        {
                            CategoryID = 6,
                            IconClass = "bi-tools",
                            Name = "Услуги"
                        },
                        new
                        {
                            CategoryID = 7,
                            IconClass = "bi-heart",
                            Name = "Животные"
                        },
                        new
                        {
                            CategoryID = 8,
                            IconClass = "bi-bicycle",
                            Name = "Хобби и спорт"
                        },
                        new
                        {
                            CategoryID = 9,
                            IconClass = "bi-lamp",
                            Name = "Мебель"
                        },
                        new
                        {
                            CategoryID = 10,
                            IconClass = "bi-three-dots",
                            Name = "Другое"
                        });
                });

            modelBuilder.Entity("Aogiri.Models.Favorite", b =>
                {
                    b.Property<int>("FavoriteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FavoriteID"));

                    b.Property<int>("AdID")
                        .HasColumnType("int");

                    b.Property<DateTime>("AddTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("FavoriteID");

                    b.HasIndex("AdID");

                    b.HasIndex("UserID");

                    b.ToTable("Favorite_6", (string)null);
                });

            modelBuilder.Entity("Aogiri.Models.Location", b =>
                {
                    b.Property<int>("LocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationID"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocationID");

                    b.ToTable("Location_3", (string)null);

                    b.HasData(
                        new
                        {
                            LocationID = 1,
                            City = "Полоцк",
                            Country = "Беларусь",
                            Region = "Витебская область"
                        },
                        new
                        {
                            LocationID = 2,
                            City = "Минск",
                            Country = "Беларусь",
                            Region = "Минская область"
                        },
                        new
                        {
                            LocationID = 3,
                            City = "Витебск",
                            Country = "Беларусь",
                            Region = "Витебская область"
                        },
                        new
                        {
                            LocationID = 4,
                            City = "Гродно",
                            Country = "Беларусь",
                            Region = "Гродненская область"
                        },
                        new
                        {
                            LocationID = 5,
                            City = "Брест",
                            Country = "Беларусь",
                            Region = "Брестская область"
                        },
                        new
                        {
                            LocationID = 6,
                            City = "Гомель",
                            Country = "Беларусь",
                            Region = "Гомельская область"
                        },
                        new
                        {
                            LocationID = 7,
                            City = "Могилев",
                            Country = "Беларусь",
                            Region = "Могилевская область"
                        },
                        new
                        {
                            LocationID = 8,
                            City = "Новополоцк",
                            Country = "Беларусь",
                            Region = "Витебская область"
                        },
                        new
                        {
                            LocationID = 9,
                            City = "Барановичи",
                            Country = "Беларусь",
                            Region = "Брестская область"
                        },
                        new
                        {
                            LocationID = 10,
                            City = "Бобруйск",
                            Country = "Беларусь",
                            Region = "Могилевская область"
                        },
                        new
                        {
                            LocationID = 11,
                            City = "Борисов",
                            Country = "Беларусь",
                            Region = "Минская область"
                        },
                        new
                        {
                            LocationID = 12,
                            City = "Пинск",
                            Country = "Беларусь",
                            Region = "Брестская область"
                        },
                        new
                        {
                            LocationID = 13,
                            City = "Орша",
                            Country = "Беларусь",
                            Region = "Витебская область"
                        },
                        new
                        {
                            LocationID = 14,
                            City = "Солигорск",
                            Country = "Беларусь",
                            Region = "Минская область"
                        },
                        new
                        {
                            LocationID = 15,
                            City = "Мозырь",
                            Country = "Беларусь",
                            Region = "Гомельская область"
                        },
                        new
                        {
                            LocationID = 16,
                            City = "Лида",
                            Country = "Беларусь",
                            Region = "Гродненская область"
                        },
                        new
                        {
                            LocationID = 17,
                            City = "Молодечно",
                            Country = "Беларусь",
                            Region = "Минская область"
                        },
                        new
                        {
                            LocationID = 18,
                            City = "Жодино",
                            Country = "Беларусь",
                            Region = "Минская область"
                        },
                        new
                        {
                            LocationID = 19,
                            City = "Слуцк",
                            Country = "Беларусь",
                            Region = "Минская область"
                        },
                        new
                        {
                            LocationID = 20,
                            City = "Несвиж",
                            Country = "Беларусь",
                            Region = "Минская область"
                        },
                        new
                        {
                            LocationID = 21,
                            City = "Жлобин",
                            Country = "Беларусь",
                            Region = "Гомельская область"
                        },
                        new
                        {
                            LocationID = 22,
                            City = "Светлогорск",
                            Country = "Беларусь",
                            Region = "Гомельская область"
                        },
                        new
                        {
                            LocationID = 23,
                            City = "Речица",
                            Country = "Беларусь",
                            Region = "Гомельская область"
                        },
                        new
                        {
                            LocationID = 24,
                            City = "Ошмяны",
                            Country = "Беларусь",
                            Region = "Гродненская область"
                        },
                        new
                        {
                            LocationID = 25,
                            City = "Волковыск",
                            Country = "Беларусь",
                            Region = "Гродненская область"
                        },
                        new
                        {
                            LocationID = 26,
                            City = "Слоним",
                            Country = "Беларусь",
                            Region = "Гродненская область"
                        },
                        new
                        {
                            LocationID = 27,
                            City = "Кобрин",
                            Country = "Беларусь",
                            Region = "Брестская область"
                        },
                        new
                        {
                            LocationID = 28,
                            City = "Пружаны",
                            Country = "Беларусь",
                            Region = "Брестская область"
                        },
                        new
                        {
                            LocationID = 29,
                            City = "Берёза",
                            Country = "Беларусь",
                            Region = "Брестская область"
                        },
                        new
                        {
                            LocationID = 30,
                            City = "Дзержинск",
                            Country = "Беларусь",
                            Region = "Минская область"
                        });
                });

            modelBuilder.Entity("Aogiri.Models.Message", b =>
                {
                    b.Property<int>("MessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageID"));

                    b.Property<int?>("AdID")
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("ReceiverID")
                        .HasColumnType("int");

                    b.Property<int>("SenderID")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MessageID");

                    b.HasIndex("AdID");

                    b.HasIndex("ReceiverID");

                    b.HasIndex("SenderID");

                    b.ToTable("Message_5", (string)null);
                });

            modelBuilder.Entity("Aogiri.Models.ModerationRule", b =>
                {
                    b.Property<int>("RuleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RuleID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phrase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RuleID");

                    b.ToTable("ModerationRule_8", (string)null);

                    b.HasData(
                        new
                        {
                            RuleID = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phrase = "только пересылка"
                        },
                        new
                        {
                            RuleID = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phrase = "бесплатно отдам"
                        },
                        new
                        {
                            RuleID = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phrase = "казино"
                        });
                });

            modelBuilder.Entity("Aogiri.Models.Report", b =>
                {
                    b.Property<int>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportID"));

                    b.Property<int>("AdID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsReviewed")
                        .HasColumnType("bit");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ReportID");

                    b.HasIndex("AdID");

                    b.HasIndex("UserID");

                    b.ToTable("Report_9", (string)null);
                });

            modelBuilder.Entity("Aogiri.Models.Subcategory", b =>
                {
                    b.Property<int>("SubcategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubcategoryID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("IconClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubcategoryID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Subcategory_11", (string)null);

                    b.HasData(
                        new
                        {
                            SubcategoryID = 1,
                            CategoryID = 1,
                            IconClass = "bi-car-front",
                            Name = "Легковые автомобили"
                        },
                        new
                        {
                            SubcategoryID = 2,
                            CategoryID = 1,
                            IconClass = "bi-bicycle",
                            Name = "Мотоциклы"
                        },
                        new
                        {
                            SubcategoryID = 3,
                            CategoryID = 1,
                            IconClass = "bi-truck",
                            Name = "Грузовики"
                        },
                        new
                        {
                            SubcategoryID = 4,
                            CategoryID = 1,
                            IconClass = "bi-gear",
                            Name = "Запчасти"
                        },
                        new
                        {
                            SubcategoryID = 5,
                            CategoryID = 1,
                            IconClass = "bi-bicycle",
                            Name = "Велосипеды"
                        },
                        new
                        {
                            SubcategoryID = 6,
                            CategoryID = 2,
                            IconClass = "bi-building",
                            Name = "Квартиры"
                        },
                        new
                        {
                            SubcategoryID = 7,
                            CategoryID = 2,
                            IconClass = "bi-house",
                            Name = "Дома и дачи"
                        },
                        new
                        {
                            SubcategoryID = 8,
                            CategoryID = 2,
                            IconClass = "bi-door-open",
                            Name = "Комнаты"
                        },
                        new
                        {
                            SubcategoryID = 9,
                            CategoryID = 2,
                            IconClass = "bi-geo",
                            Name = "Земельные участки"
                        },
                        new
                        {
                            SubcategoryID = 10,
                            CategoryID = 2,
                            IconClass = "bi-shop",
                            Name = "Коммерческая"
                        },
                        new
                        {
                            SubcategoryID = 11,
                            CategoryID = 3,
                            IconClass = "bi-phone",
                            Name = "Телефоны"
                        },
                        new
                        {
                            SubcategoryID = 12,
                            CategoryID = 3,
                            IconClass = "bi-laptop",
                            Name = "Ноутбуки и ПК"
                        },
                        new
                        {
                            SubcategoryID = 13,
                            CategoryID = 3,
                            IconClass = "bi-tablet",
                            Name = "Планшеты"
                        },
                        new
                        {
                            SubcategoryID = 14,
                            CategoryID = 3,
                            IconClass = "bi-tv",
                            Name = "Телевизоры"
                        },
                        new
                        {
                            SubcategoryID = 15,
                            CategoryID = 3,
                            IconClass = "bi-music-note",
                            Name = "Аудио и видео"
                        },
                        new
                        {
                            SubcategoryID = 16,
                            CategoryID = 3,
                            IconClass = "bi-camera",
                            Name = "Фото и видео"
                        },
                        new
                        {
                            SubcategoryID = 17,
                            CategoryID = 4,
                            IconClass = "bi-person",
                            Name = "Мужская одежда"
                        },
                        new
                        {
                            SubcategoryID = 18,
                            CategoryID = 4,
                            IconClass = "bi-person",
                            Name = "Женская одежда"
                        },
                        new
                        {
                            SubcategoryID = 19,
                            CategoryID = 4,
                            IconClass = "bi-star",
                            Name = "Детская одежда"
                        },
                        new
                        {
                            SubcategoryID = 20,
                            CategoryID = 4,
                            IconClass = "bi-bag",
                            Name = "Обувь"
                        },
                        new
                        {
                            SubcategoryID = 21,
                            CategoryID = 4,
                            IconClass = "bi-watch",
                            Name = "Аксессуары"
                        },
                        new
                        {
                            SubcategoryID = 22,
                            CategoryID = 5,
                            IconClass = "bi-code-slash",
                            Name = "IT и интернет"
                        },
                        new
                        {
                            SubcategoryID = 23,
                            CategoryID = 5,
                            IconClass = "bi-hammer",
                            Name = "Строительство"
                        },
                        new
                        {
                            SubcategoryID = 24,
                            CategoryID = 5,
                            IconClass = "bi-cart",
                            Name = "Торговля"
                        },
                        new
                        {
                            SubcategoryID = 25,
                            CategoryID = 5,
                            IconClass = "bi-heart-pulse",
                            Name = "Медицина"
                        },
                        new
                        {
                            SubcategoryID = 26,
                            CategoryID = 5,
                            IconClass = "bi-book",
                            Name = "Образование"
                        },
                        new
                        {
                            SubcategoryID = 27,
                            CategoryID = 6,
                            IconClass = "bi-tools",
                            Name = "Ремонт и строительство"
                        },
                        new
                        {
                            SubcategoryID = 28,
                            CategoryID = 6,
                            IconClass = "bi-scissors",
                            Name = "Красота и здоровье"
                        },
                        new
                        {
                            SubcategoryID = 29,
                            CategoryID = 6,
                            IconClass = "bi-book",
                            Name = "Репетиторство"
                        },
                        new
                        {
                            SubcategoryID = 30,
                            CategoryID = 6,
                            IconClass = "bi-truck",
                            Name = "Перевозки"
                        },
                        new
                        {
                            SubcategoryID = 31,
                            CategoryID = 7,
                            IconClass = "bi-heart",
                            Name = "Собаки"
                        },
                        new
                        {
                            SubcategoryID = 32,
                            CategoryID = 7,
                            IconClass = "bi-heart",
                            Name = "Кошки"
                        },
                        new
                        {
                            SubcategoryID = 33,
                            CategoryID = 7,
                            IconClass = "bi-feather",
                            Name = "Птицы"
                        },
                        new
                        {
                            SubcategoryID = 34,
                            CategoryID = 7,
                            IconClass = "bi-droplet",
                            Name = "Рыбки и аквариумы"
                        },
                        new
                        {
                            SubcategoryID = 35,
                            CategoryID = 8,
                            IconClass = "bi-trophy",
                            Name = "Спортивный инвентарь"
                        },
                        new
                        {
                            SubcategoryID = 36,
                            CategoryID = 8,
                            IconClass = "bi-backpack",
                            Name = "Туризм и отдых"
                        },
                        new
                        {
                            SubcategoryID = 37,
                            CategoryID = 8,
                            IconClass = "bi-book",
                            Name = "Книги и журналы"
                        },
                        new
                        {
                            SubcategoryID = 38,
                            CategoryID = 8,
                            IconClass = "bi-music-note-beamed",
                            Name = "Музыкальные инструменты"
                        },
                        new
                        {
                            SubcategoryID = 39,
                            CategoryID = 9,
                            IconClass = "bi-lamp",
                            Name = "Спальня"
                        },
                        new
                        {
                            SubcategoryID = 40,
                            CategoryID = 9,
                            IconClass = "bi-tv",
                            Name = "Гостиная"
                        },
                        new
                        {
                            SubcategoryID = 41,
                            CategoryID = 9,
                            IconClass = "bi-cup-hot",
                            Name = "Кухня"
                        },
                        new
                        {
                            SubcategoryID = 42,
                            CategoryID = 9,
                            IconClass = "bi-briefcase",
                            Name = "Офисная мебель"
                        });
                });

            modelBuilder.Entity("Aogiri.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Active");

                    b.HasKey("UserID");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("User_1", (string)null);

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Login = "admin",
                            Name = "Администратор",
                            PasswordHash = "$2a$11$NKjkwTwLu6KLCU0On5/y4um4rbvXPAZ9EfYel3pz.3QCUK0z5BnA6",
                            Phone = "+375291234567",
                            RegDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Role = "Admin",
                            Status = "Active"
                        },
                        new
                        {
                            UserID = 2,
                            Login = "moder",
                            Name = "Модератор",
                            PasswordHash = "$2a$11$47bl0ES41utvX0yTFdDNEe3E4Qj2XGrx1uiVR9F1MYqzoTkTesgvi",
                            Phone = "+375297654321",
                            RegDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Role = "Moderator",
                            Status = "Active"
                        },
                        new
                        {
                            UserID = 3,
                            Login = "user1",
                            Name = "Иван Иванов",
                            PasswordHash = "$2a$11$NEWfnId0jt.xm1mfW8b8QewkDrwbufrntAaaPL0NVN.xhq99Z35vq",
                            Phone = "+375291111111",
                            RegDate = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Role = "User",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("Aogiri.Models.ActivityLog", b =>
                {
                    b.HasOne("Aogiri.Models.User", "User")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aogiri.Models.AdAttribute", b =>
                {
                    b.HasOne("Aogiri.Models.Advertisement", "Advertisement")
                        .WithMany("Attributes")
                        .HasForeignKey("AdID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advertisement");
                });

            modelBuilder.Entity("Aogiri.Models.AdImage", b =>
                {
                    b.HasOne("Aogiri.Models.Advertisement", "Advertisement")
                        .WithMany("Images")
                        .HasForeignKey("AdID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advertisement");
                });

            modelBuilder.Entity("Aogiri.Models.Advertisement", b =>
                {
                    b.HasOne("Aogiri.Models.Category", "Category")
                        .WithMany("Advertisements")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Aogiri.Models.Location", "Location")
                        .WithMany("Advertisements")
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Aogiri.Models.Subcategory", "Subcategory")
                        .WithMany("Advertisements")
                        .HasForeignKey("SubcategoryID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Aogiri.Models.User", "User")
                        .WithMany("Advertisements")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Location");

                    b.Navigation("Subcategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aogiri.Models.Favorite", b =>
                {
                    b.HasOne("Aogiri.Models.Advertisement", "Advertisement")
                        .WithMany("Favorites")
                        .HasForeignKey("AdID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aogiri.Models.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advertisement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aogiri.Models.Message", b =>
                {
                    b.HasOne("Aogiri.Models.Advertisement", "Advertisement")
                        .WithMany("Messages")
                        .HasForeignKey("AdID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Aogiri.Models.User", "Receiver")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("ReceiverID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Aogiri.Models.User", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Advertisement");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Aogiri.Models.Report", b =>
                {
                    b.HasOne("Aogiri.Models.Advertisement", "Advertisement")
                        .WithMany()
                        .HasForeignKey("AdID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aogiri.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Advertisement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aogiri.Models.Subcategory", b =>
                {
                    b.HasOne("Aogiri.Models.Category", "Category")
                        .WithMany("Subcategories")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Aogiri.Models.Advertisement", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("Favorites");

                    b.Navigation("Images");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Aogiri.Models.Category", b =>
                {
                    b.Navigation("Advertisements");

                    b.Navigation("Subcategories");
                });

            modelBuilder.Entity("Aogiri.Models.Location", b =>
                {
                    b.Navigation("Advertisements");
                });

            modelBuilder.Entity("Aogiri.Models.Subcategory", b =>
                {
                    b.Navigation("Advertisements");
                });

            modelBuilder.Entity("Aogiri.Models.User", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("Advertisements");

                    b.Navigation("Favorites");

                    b.Navigation("ReceivedMessages");

                    b.Navigation("SentMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
