// <auto-generated />
using System;
using Aogiri.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aogiri.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Aogiri.Models.ActivityLog", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogID"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("LogID");

                    b.HasIndex("UserID");

                    b.ToTable("ActivityLog_7", (string)null);
                });

            modelBuilder.Entity("Aogiri.Models.Advertisement", b =>
                {
                    b.Property<int>("AdID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocationID")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<DateTime>("PublishedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Draft");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("AdID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("LocationID");

                    b.HasIndex("UserID");

                    b.ToTable("Advertisement_4", (string)null);
                });

            modelBuilder.Entity("Aogiri.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("IconClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Category_2", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            IconClass = "bi-car-front",
                            Name = "Транспорт"
                        },
                        new
                        {
                            CategoryID = 2,
                            IconClass = "bi-house",
                            Name = "Недвижимость"
                        },
                        new
                        {
                            CategoryID = 3,
                            IconClass = "bi-laptop",
                            Name = "Электроника"
                        },
                        new
                        {
                            CategoryID = 4,
                            IconClass = "bi-bag",
                            Name = "Одежда и обувь"
                        },
                        new
                        {
                            CategoryID = 5,
                            IconClass = "bi-briefcase",
                            Name = "Работа"
                        },
                        new
                        {
                            CategoryID = 6,
                            IconClass = "bi-tools",
                            Name = "Услуги"
                        },
                        new
                        {
                            CategoryID = 7,
                            IconClass = "bi-heart",
                            Name = "Животные"
                        },
                        new
                        {
                            CategoryID = 8,
                            IconClass = "bi-bicycle",
                            Name = "Хобби и спорт"
                        },
                        new
                        {
                            CategoryID = 9,
                            IconClass = "bi-lamp",
                            Name = "Мебель"
                        },
                        new
                        {
                            CategoryID = 10,
                            IconClass = "bi-three-dots",
                            Name = "Другое"
                        });
                });

            modelBuilder.Entity("Aogiri.Models.Favorite", b =>
                {
                    b.Property<int>("FavoriteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FavoriteID"));

                    b.Property<int>("AdID")
                        .HasColumnType("int");

                    b.Property<DateTime>("AddTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("FavoriteID");

                    b.HasIndex("AdID");

                    b.HasIndex("UserID");

                    b.ToTable("Favorite_6", (string)null);
                });

            modelBuilder.Entity("Aogiri.Models.Location", b =>
                {
                    b.Property<int>("LocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationID"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocationID");

                    b.ToTable("Location_3", (string)null);

                    b.HasData(
                        new
                        {
                            LocationID = 1,
                            City = "Полоцк",
                            Country = "Беларусь",
                            Region = "Витебская область"
                        },
                        new
                        {
                            LocationID = 2,
                            City = "Минск",
                            Country = "Беларусь",
                            Region = "Минская область"
                        },
                        new
                        {
                            LocationID = 3,
                            City = "Витебск",
                            Country = "Беларусь",
                            Region = "Витебская область"
                        },
                        new
                        {
                            LocationID = 4,
                            City = "Гродно",
                            Country = "Беларусь",
                            Region = "Гродненская область"
                        },
                        new
                        {
                            LocationID = 5,
                            City = "Брест",
                            Country = "Беларусь",
                            Region = "Брестская область"
                        },
                        new
                        {
                            LocationID = 6,
                            City = "Гомель",
                            Country = "Беларусь",
                            Region = "Гомельская область"
                        },
                        new
                        {
                            LocationID = 7,
                            City = "Могилев",
                            Country = "Беларусь",
                            Region = "Могилевская область"
                        });
                });

            modelBuilder.Entity("Aogiri.Models.Message", b =>
                {
                    b.Property<int>("MessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageID"));

                    b.Property<int?>("AdID")
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("ReceiverID")
                        .HasColumnType("int");

                    b.Property<int>("SenderID")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MessageID");

                    b.HasIndex("AdID");

                    b.HasIndex("ReceiverID");

                    b.HasIndex("SenderID");

                    b.ToTable("Message_5", (string)null);
                });

            modelBuilder.Entity("Aogiri.Models.ModerationRule", b =>
                {
                    b.Property<int>("RuleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RuleID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phrase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RuleID");

                    b.ToTable("ModerationRule_8", (string)null);

                    b.HasData(
                        new
                        {
                            RuleID = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phrase = "только пересылка"
                        },
                        new
                        {
                            RuleID = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phrase = "бесплатно отдам"
                        },
                        new
                        {
                            RuleID = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phrase = "казино"
                        });
                });

            modelBuilder.Entity("Aogiri.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Active");

                    b.HasKey("UserID");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("User_1", (string)null);

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Login = "admin",
                            Name = "Администратор",
                            PasswordHash = "$2a$11$nkwBOrzbgCICBe1dQSSioeq4KQ1tcpAaEnISfUmC0.O5pxjGWjJam",
                            Phone = "+375291234567",
                            RegDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Role = "Admin",
                            Status = "Active"
                        },
                        new
                        {
                            UserID = 2,
                            Login = "moder",
                            Name = "Модератор",
                            PasswordHash = "$2a$11$d23u.U1JVX8L/fntQ0ee5OYN2/e.vlXc3t3Euk1TpW/5DrC5gx59e",
                            Phone = "+375297654321",
                            RegDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Role = "Moderator",
                            Status = "Active"
                        },
                        new
                        {
                            UserID = 3,
                            Login = "user1",
                            Name = "Иван Иванов",
                            PasswordHash = "$2a$11$coETBOh9tiXJBkJifV9WW.1x7Ix3gwmNMYZG3E/cZ5Yk3UhYS/EV2",
                            Phone = "+375291111111",
                            RegDate = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Role = "User",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("Aogiri.Models.ActivityLog", b =>
                {
                    b.HasOne("Aogiri.Models.User", "User")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aogiri.Models.Advertisement", b =>
                {
                    b.HasOne("Aogiri.Models.Category", "Category")
                        .WithMany("Advertisements")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Aogiri.Models.Location", "Location")
                        .WithMany("Advertisements")
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Aogiri.Models.User", "User")
                        .WithMany("Advertisements")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Location");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aogiri.Models.Favorite", b =>
                {
                    b.HasOne("Aogiri.Models.Advertisement", "Advertisement")
                        .WithMany("Favorites")
                        .HasForeignKey("AdID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aogiri.Models.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advertisement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aogiri.Models.Message", b =>
                {
                    b.HasOne("Aogiri.Models.Advertisement", "Advertisement")
                        .WithMany("Messages")
                        .HasForeignKey("AdID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Aogiri.Models.User", "Receiver")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("ReceiverID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Aogiri.Models.User", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Advertisement");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Aogiri.Models.Advertisement", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Aogiri.Models.Category", b =>
                {
                    b.Navigation("Advertisements");
                });

            modelBuilder.Entity("Aogiri.Models.Location", b =>
                {
                    b.Navigation("Advertisements");
                });

            modelBuilder.Entity("Aogiri.Models.User", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("Advertisements");

                    b.Navigation("Favorites");

                    b.Navigation("ReceivedMessages");

                    b.Navigation("SentMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
